language: 
  - python
python:
  - "3.6.7"

services:
  - postgresql
  
env: 
  -DJANGO=2.2.1 

# before_install:
#   - export DJANGO_SETTINGS_MODULE = ApiProject.settings

install:

  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE prodduct;" -U postgres    

script:
  - python manage.py syncdb --noinput
  - python manage.py test

